spring:
  datasource:
    url: jdbc:postgresql://hattie.db.elephantsql.com:5432/qdddkklm
    username: qdddkklm
    password: p4w7KnEgZgi71LIYoJu7oeUOzOImirwt
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    open-in-view: false
springdoc:
  swagger-ui:
    operations-sorter: method
    path: /swagger-ui.html
